### ISSUE TITLE
Zoom feature disabled when switching between Tobii instances on the same page

### ISSUE THREAD

**Issue by mably** [rqrauhvmra/Tobii#121] opened 2024-12-17 09:29 UTC
Can be reproduced on the [demo page](https://midzer.github.io/tobii/demo/):

<img width="512" alt="image" src="https://github.com/user-attachments/assets/10147009-a8ec-4dee-b9b8-186864a2ba9b" />

Click on the first top left image and use the zoom feature by using the mouse wheel.

Then close the lightbox and click on the first image in the second row.

Once the lightbox is open, try to zoom using the mouse wheel,  you'll see that it doesn't work.

The `TRANSFORM.element` variable doesn't seem to have been properly reset when switching lightbox instances.

**Comment by midzer** [comment] 2024-12-17 09:39
Hi @mably and thanks for filing :)

Right now, I can't reproduce this issue.

When tobii is closed or slides change, zoom should be reset via

https://github.com/midzer/tobii/blob/725ca346b7f5eb1f7002979047bb9fcfb451ba60/src/js/index.js#L750

**Comment by mably** [comment] 2024-12-17 09:44
I have been able to rather consistently reproduce the bug on Chrome, Safari and Firefox on MacOS Sonoma.

**Comment by mably** [comment] 2024-12-17 09:55
![image](https://github.com/user-attachments/assets/ec6695ac-4553-4085-9fc4-c5317ae1dc8c)

**Comment by mably** [comment] 2024-12-17 09:55
![tobii-zoom-bug](https://github.com/user-attachments/assets/bd2bfdf1-e2c0-4232-bf93-26983d339bf1)

**Comment by midzer** [comment] 2024-12-17 10:01
Okay, now I can reproduce:

* Zoom in AND out (completely) on first picture
* Then zoom is broken on the 2nd one

I'm on it for a fix.

**Comment by midzer** [comment] 2024-12-17 10:19
Fixed by https://github.com/midzer/tobii/commit/1ddba48e8f9acf7c5f41f5201f129d9e130f690d

Thanks again for reporting @mably

**Comment by mably** [comment] 2024-12-17 10:20
You're welcome @midzer, that was a quick fix! Thanks.

**Comment by mably** [comment] 2024-12-17 10:34
Don't know if it's related, but I'm getting those errors in my browser console now:

```
tobii.umd.js?somvmf:1406 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at pan (tobii.umd.js?somvmf:1406:15)
    at resetZoom (tobii.umd.js?somvmf:1437:7)
    at cleanup (tobii.umd.js?somvmf:1042:7)
    at close (tobii.umd.js?somvmf:842:7)
    at HTMLDivElement.clickHandler (tobii.umd.js?somvmf:1145:9)
```

**Comment by midzer** [comment] 2024-12-17 10:36
Damn...hang on.

**Comment by midzer** [comment] 2024-12-17 10:47
@mably Okay...another try https://github.com/midzer/tobii/commit/0d89c964b231375279677b79b5e66297d17abcb5

Can you test also before I release? :)

**Comment by mably** [comment] 2024-12-17 11:30
Yep sure.

**Comment by mably** [comment] 2024-12-17 11:32
Seems to work fine on my side 👍

**Closed as completed** 2024-12-17 14:12 UTC
